version: "3"
services:
  nginx:
    image: nginx:1.18
    container_name: seernginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /srv/seer/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /srv/seer/nginx/http:/srv/http
  tomcat:
    image: tomcat:9.0-jdk8-openjdk
    container_name: seertomcat
    restart: unless-stopped
    volumes:
      - /srv/seer/tomcat/webapps:/usr/local/tomcat/webapps
  mysql:
    image: mysql:8.0.23
    container_name: seermysql
    restart: unless-stopped
    volumes:
      - /srv/seer/mysql/data:/var/lib/mysql
      - /srv/seer/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
