version: "3"
services:
  nginx:
    image: nginx:1.18
    container_name: seernginx
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../seer-www/:/srv/http
  springboot:
    depends_on:
      - mysql
    build: ../seer-server
    container_name: seerspringboot
    restart: unless-stopped
  mysql:
    image: mysql:8.0.23
    container_name: seermysql
    restart: unless-stopped
    # 解决中文编码问题
    command: ["--default-authentication-plugin=mysql_native_password",  "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci",  "--skip-character-set-client-handshake"]
    volumes:
      # 解决占用内存过大的问题
      - ./mysql/customer.cnf:/etc/mysql/conf.d/customer.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

