version: "3"
services:
  nginx:
    image: nginx:1.18
    container_name: seernginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../seer-www/:/srv/http
  tomcat:
    image: tomcat:9.0-jdk8-openjdk
    container_name: seertomcat
    restart: unless-stopped
    volumes:
      - ../seer-server/target/seer.war:/usr/local/tomcat/webapps/seer.war
  mysql:
    image: mysql:8.0.23
    container_name: seermysql
    restart: unless-stopped
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
