version: "3"
services:
  nginx:
    image: nginx:1.18
    container_name: seernginx
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../seer-www/:/srv/http
  springboot:
    depends_on:
      - mysql
    build: ../seer-server
    container_name: seerspringboot
    restart: unless-stopped
  mysql:
    image: mysql:8.0.23
    container_name: seermysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
