spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seer?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    com.sd.seerserver: DEBUG
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"

