server:
  port: 9090
  servlet:
    context-path: /s

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://seermysql:3306/seer?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    com.sd.seerserver: WARN
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  file:
    name: log.log

swagger:
  enable: false